node { 
    stage('Clone repository') { 
        git credentialsId: 'github-access', url: 'https://github.com/JANGSEOKHAN/jenkins1' 
    } 
 
    stage('Build image') { 
       dockerImage = docker.build("jangseokhan123/node-front:1.0", "-f docker-project-front/Dockerfile .") 
    } 
 
 stage('Push image') { 
        withDockerRegistry([ credentialsId: "docker-access", url: "" ]) { 
        dockerImage.push() 
        } 
    } 
}
